name: 'revenue_leak'
version: '1.0.0'

profile: 'revenue_leak'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  revenue_leak:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
